name: Deploy snapshot to central

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    needs: build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v3
      - uses: actions/cache@v4
        with:
          path: |
            ~/.konan
          key: ${{ runner.os }}-${{ hashFiles('**/.lock') }}
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
          passphrase: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Show Version Number
        id: version
        run: |
          echo "Version=${{ github.event.release.tag_name }}"
      - name: Gradle buildDict
        uses: gradle/gradle-build-action@ac2d340dc04d9e1113182899e983b5400c17cda1
        with:
          arguments: :momiji-ipadic-code:buildDict :momiji-ipadic-resources:buildDict
      - name: Gradle publish
        uses: gradle/gradle-build-action@ac2d340dc04d9e1113182899e983b5400c17cda1
        with:
          arguments: |
            -PmavenCentralUsername=${{secrets.OSSRH_USERNAME}}
            -PmavenCentralPassword=${{secrets.OSSRH_PASSWORD}}
            -PsigningInMemoryKeyId=${{secrets.OSSRH_GPG_SECRET_KEY_ID}}
            -PsigningInMemoryPassword=${{secrets.OSSRH_GPG_SECRET_KEY_PASSWORD}}
            publishAllPublicationsToMavenCentralRepository
        env:
          LIB_VERSION: ${{ github.event.release.tag_name }}
